Feature: Instatus

Scenario: initialize_not_empty_list delete_a_incident_from_list get_incidents verify_size_list not_empty_list create_new_incident  

Given initialize_not_empty_list
When delete_a_incident_from_list
Then deleteSuccess
When get_incidents
And verify_size_list
And not_empty_list
Then verifyNotEmptyList
When create_new_incident
Then creationSuccess


Scenario: initialize_not_empty_list create_new_incident view_created_incident_details  

Given initialize_not_empty_list
When create_new_incident
Then creationSuccess
When view_created_incident_details
Then incidentActiveSuccess


Scenario: initialize_not_empty_list view_incident_details update_an_incident view_updated_incident_details  

Given initialize_not_empty_list
When view_incident_details
Then incidentActiveSuccess
When update_an_incident
Then updateSuccess
When view_updated_incident_details
Then incidentActiveSuccess


Scenario: initialize_not_empty_list view_incident_details delete_this_incident  

Given initialize_not_empty_list
When view_incident_details
Then incidentActiveSuccess
When delete_this_incident
Then deleteSuccess


Scenario: initialize_not_empty_list delete_a_incident_from_list get_incidents verify_size_list empty_list create_new_incident  

Given initialize_not_empty_list
When delete_a_incident_from_list
Then deleteSuccess
When get_incidents
And verify_size_list
And empty_list
Then verifyEmptyList
When create_new_incident
Then creationSuccess


